name: Build Electron app


on:
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node version'
        type: string
        default: 18.x

jobs:
  build-mac:
    runs-on: macOS-latest
    name: Build on MacOS
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ github.events.inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ github.events.inputs.node_version }}
      - run: |
              export SCHEMIO_VERSION=$(node -pe "require('./package.json').version")
              echo "::set-env name=SCHEMIO_VERSION::$SCHEMIO_VERSION"
      - run: npm ci
      - run: npm run package-electron
      - run: npm run make-electron
      - run: find out | grep -v .webpack/renderer/assets
      - uses: actions/upload-artifact@v3
        with:
          name: schemio-electron-mac.zip
          path: out/make/zip/darwin/x64/schemio-darwin-x64-${{ env.SCHEMIO_VERSION }}.zip


  build-linux:
    runs-on: ubuntu-latest
    name: Build on Linux
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ github.events.inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ github.events.inputs.node_version }}
      - run: |
              export SCHEMIO_VERSION=$(node -pe "require('./package.json').version")
              echo "::set-env name=SCHEMIO_VERSION::$SCHEMIO_VERSION"
      - run: npm ci
      - run: npm run package-electron
      - run: npm run make-electron
      - run: find out | grep -v .webpack/renderer/assets
      - uses: actions/upload-artifact@v3
        with:
          name: schemio-electron-linux.rpm
          path: out/make/rpm/x64/schemio-${{ env.SCHEMIO_VERSION }}-1.x86_64.rpm
      - uses: actions/upload-artifact@v3
        with:
          name: schemio-electron-linux.deb
          path: out/make/deb/x64/schemio_${{ env.SCHEMIO_VERSION }}_amd64.deb

  build-win:
    name: Build Windows app
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ github.events.inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ github.events.inputs.node_version }}
      - run: |
              export SCHEMIO_VERSION=$(node -pe "require('./package.json').version")
              echo "::set-env name=SCHEMIO_VERSION::$SCHEMIO_VERSION"
      - run: npm ci
      - run: npm run package-electron
      - run: npm run make-electron
      - run: npm install -g tree-cli
      - run: cd out && tree -l 8
      - uses: actions/upload-artifact@v3
        with:
          name: schemio-electron-win-setup.exe
          path: out/make/squirrel.windows/x64/schemio-${{ env.SCHEMIO_VERSION }} Setup.exe
