name: Trigger Electron release upload


on:
  workflow_dispatch:
    inputs:
      schemio_version:
        description: 'Schemio version'
        type: string
        default: '0.1.0'
      node_version:
        description: 'Node version'
        type: string
        default: 18.x

jobs:
  call-electron-build:
    needs: extract-version
    uses: ./.github/workflows/build-electron.yaml
    with:
      node_version: ${{ github.events.inputs.node_version }}
      schemio_version: ${{ github.events.inputs.schemio_version }}
      attach_to_release: true

